// copy-zk.mjs - publishes the amparo contract's ZK assets as static files.
//
// The browser fetches proving keys over HTTP from this origin, so they have to
// be part of the built app. They are compiler output: gitignored, several
// megabytes, and regenerated by `compact compile` under WSL.
//
// Failing loudly here is the point. Missing keys otherwise surface as a 404
// during proving - seconds after the user pressed a button, from inside a
// dependency - which reads like a circuit problem and is a deployment one.

import { cp, access, rm } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';

const SOURCE = fileURLToPath(new URL('../../contracts/src/managed/amparo', import.meta.url));
const PUBLISHED = fileURLToPath(new URL('../public/zk', import.meta.url));
const TARGET = fileURLToPath(new URL('../public/zk/amparo', import.meta.url));

try {
  await access(SOURCE);
} catch {
  console.error(
    `No compiled contract at ${SOURCE}.\n` +
      'Compile it first, from WSL:\n' +
      '  compact compile src/amparo.compact src/managed/amparo\n' +
      'Never `npm run compile` from Windows: `compact` is also the NTFS compression tool, ' +
      'which returns 0 without compiling anything.',
  );
  process.exit(1);
}

// The WHOLE published directory goes, not just this contract's subdirectory.
//
// Clearing only the target is what an earlier version did, and it does not
// hold: renaming the contract leaves the previous name's keys published under
// their old path, still served, indistinguishable from current ones. Measured
// here - 15 MB of proving keys for a contract that no longer exists, answering
// 200. Nothing catches it: the directory is gitignored so it never appears in a
// diff, and the app only ever fetches its own path, so every check stays green
// while the stale set sits next to the live one.
//
// Wiping the directory makes what is published exactly what the compiler just
// emitted, which is the property the copy is supposed to have.
await rm(PUBLISHED, { recursive: true, force: true });
await cp(SOURCE, TARGET, { recursive: true });
console.log(`Published ZK assets to ${TARGET}`);
