// copy-zk.mjs - publishes the filing registry's ZK assets as static files.
//
// The browser fetches proving keys over HTTP from this origin, so they have to
// be part of the built app. They are compiler output: gitignored, several
// megabytes, and regenerated by `compact compile` under WSL.
//
// Failing loudly here is the point. Missing keys otherwise surface as a 404
// during proving - seconds after the user pressed a button, from inside a
// dependency - which reads like a circuit problem and is a deployment one.

import { cp, access, rm } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';

const SOURCE = fileURLToPath(new URL('../../contracts/src/managed/filing_registry', import.meta.url));
const TARGET = fileURLToPath(new URL('../public/zk/filing_registry', import.meta.url));

try {
  await access(SOURCE);
} catch {
  console.error(
    `No compiled contract at ${SOURCE}.\n` +
      'Compile it first, from WSL:\n' +
      '  compact compile src/filing_registry.compact src/managed/filing_registry\n' +
      'Never `npm run compile` from Windows: `compact` is also the NTFS compression tool, ' +
      'which returns 0 without compiling anything.',
  );
  process.exit(1);
}

// Removed first so a stale key from a previous circuit cannot survive a rebuild
// and be served alongside new ones.
await rm(TARGET, { recursive: true, force: true });
await cp(SOURCE, TARGET, { recursive: true });
console.log(`Published ZK assets to ${TARGET}`);
